const languageStrings = {
  en: {
    login_title: 'Login to your account',
    login_sub_title: 'Regimen provides the most suitable packages you need to build a healthy body',
    phone_number_placeholder: 'Phone number',
    verification_code_placeholder: 'Verification code',
    login_button_text: 'Login',
    profile_title: 'Profile',
    profile_section_title: 'Profile',
    add_address_title: 'Add Addresses',
    add_vacation_title: 'Add Vacation',
    privacy_section_title: 'Privacy',
    privacy_policy_title: 'Privacy Policy',
    terms_and_conditions_title: 'Terms and Conditions',
    about_app_title: 'About the App',
    technical_support_title: 'Technical Support',
    contact_us_title: 'Contact Us',
    logout_button_text: 'Log out',
    language_title: 'Language',
    language_header: 'Language Settings',
    contact_header: 'Contact Us',
    titlePlaceholder: 'Message title',
    fileUploadPlaceholder: 'Upload file',
    messagePlaceholder: 'Message',
    sendButtonText: 'Send',
    ctext1:'Contact us via',
    ctext2:'or you can send a text message to the support team',
    number_of_meals:'Number of meals consumed',
    todays_meal:"Today's Meals",
    no_meals:'No Meals Currently',
    meal_message:"It seems you haven't subscribed to any plan yet. Once you subscribe, all your plans will appear here.",
    subscribe_plan:'Subscribe to a Plan',
    htext1:'You are currently subscribed to the',
    htext2:'since ',
    htext3:'and will expire in 26 days on',
    terms_and_conditions_content: `
  This text is an example of text that can be replaced in the same area. This text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application.
  \n
  This text is an example of text that can be replaced in the same area. This text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application.
  \n
  This text is an example of text that can be replaced in the same area. This text has been generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application.
`,
 terms_and_conditions_ptitle:'Terms and Conditions'
  },
  ar: {
    login_title: 'تسجيل الدخول إلى حسابك',
    login_sub_title: 'رجيم يمنحك الباقات الأنسب لك التي تحتاجها لبناء جسم صحي',
    phone_number_placeholder: 'رقم الهاتف',
    verification_code_placeholder: 'رمز التحقق',
    login_button_text: 'تسجيل الدخول',
    profile_title: 'البروفايل',
    profile_section_title: 'البروفايل',
    add_address_title: 'إضافة العناوين',
    add_vacation_title: 'إضافة إجازة',
    privacy_section_title: 'الخصوصية',
    privacy_policy_title: 'سياسة الخصوصية',
    terms_and_conditions_title: 'الشروط والأحكام',
    about_app_title: 'عن التطبيق',
    technical_support_title: 'الدعم الفني',
    contact_us_title: 'تواصل معنا',
    logout_button_text: 'تسجيل الخروج',
    language_title: 'اللغة',
    language_header: 'إعدادات اللغة',
    contact_header: 'تواصل معنا',
    titlePlaceholder: 'عنوان الرسالة',
    fileUploadPlaceholder: 'رفع ملف',
    messagePlaceholder: 'الرسالة',
    sendButtonText: 'إرسال',
    ctext1:'تواصل معنا عبر',
    ctext2:'أو يمكنك إرسال رسالة نصية إلى فريق الدعم',
    number_of_meals:'عدد الوجبات المستهلكة',
    todays_meal:"وجبات اليوم",
    no_meals:'لا توجد وجبات حاليا',
    meal_message:"يبدو أنك لم تشترك في أي خطة حتى الآن. بمجرد الاشتراك ، ستظهر جميع خططك هنا.",
    subscribe_plan:'الاشتراك في خطة',
    htext1:'أنت مشترك حاليا في',
    htext2:'منذ',
    htext3:'وستنتهي صلاحيتها في غضون 26 يوما',
    terms_and_conditions_content: `
  هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.
  \n
  هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.
  \n
  هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.`,
  terms_and_conditions_ptitle:'Terms and Conditions'
  },
};

export default languageStrings;